name: Devsecops_CiCD Pipeline

on:
  push:
    branches: [feature/security]

  pull_request:
    branches: [feature/security]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Bandit
        run: pip install bandit

      - name: Run Security Scan
        run: bandit -r . -f json -o bandit-report.json
