name: Devsecops_CiCD Pipeline

on:
  push:
    branches: [feature/security]
  pull_request:
    branches: [feature/security]
jobs:
 security:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - name: Run Security Scan
       run: |
        pip install bandit
        bandit -r -f json 
